resource/ui/itemselectionpanel.res, resource/ui/mainmenuoverride.res
Also fix a typo on mainmenu FooterLine (-50 instead of -5-, but -50 doesn't properly place it in front of the footer, so -49).
The crafting menu item tooltips think they have too much space available and get hidden behind the footer area.
Old:
New:
For reference:
https://github.com/Eniere/idhud/pull/2
=> Fix item description tooltips being cut off in crafting menu

resource/ui/mainmenuoverride.res
This commit does the following to make it in-line with live TF2:
1. Remove the StreamListPanel, as now it has been removed from the official HUD files and the button simply links to the Twitch page
2. Replace Winter 2019 cases on the market panel with Summer 2020 ones.
I simply took the current HUD file and merged these 2 differences.
=> Fixes for the August 21st patch.

resource/ui/itemquickswitch.res
This prevents the item container panels from moving too far to the left when scrolling in the quickswitch menu. This is an issue with most HUDs in TF2, which can be fixed by subtracting 30 from the xpos value in "itemcontainer" and then adding 30 to the xpos value "itemcontainerscroller". "itemcontainerscroller"'s wide value also gets subtracted by 25 to let the scroll bar still be visible and not too out of place before colliding with the item panels.
=> Fix quickswitch scroller moving item containers

resource/ui/spectator.res, scripts/hudlayout.res
These are quick fixes to resolve #48 and #49.
The former switches the location of the map / class info in the spectator camera to the left side and disables the tips so that the items info can stay in its cool corner.
The latter was brought down a little bit so that long names don't bump into dead players.
=> Fix for spectator camera

resource/ui/charinfopanel.res, resource/ui/econ/store/v2/storepanel.res, resource/ui/replaybrowser/mainpanel.res
Related to #53 and #54.
This changes the position of inventory, store, and replay back buttons to match the main menu's counterpart. Before this change, there is a small pixel difference because it doesn't use the same values (ypos 437 -> rs1-18).
=> Correct back button positions

resource/ui/pvprankpanel.res
This fixes issue #43, where the "XPBar" doesn't show properly.
=> Fix XPBar not showing on Casual Results Screen

resource/ui/hudmannvsmachinestatus.res, scripts/hudlayout.res
The MvM currency panel stopped showing after this year's Smissmas update because `CurrencyStatusPanel` got moved: https://github.com/Hypnootize/TF2-Default-HUD/commit/1824596664bec02528a3f258d02b7d33d5be246b
=> Move CurrencyStatusPanel to scripts/hudlayout.res

resource/ui/huditemeffectmeter_pomson.res
For minimal hud mode
All other meters are at a small distance from the edge of the screen, with the exception of the pomson.
=> Fix pomson meter position

resource/ui/#customizations/crosshair/crosshair_scheme.res
literally just removes one letter to fix custom crosshairs
Before
After
Before
After
=> Fix for custom crosshair characters

resource/ui/hudmatchsummary.res
These problems are not present in the default hud, I just fixed my mistakes
This happened when there were more than 12 players on a team (such as in Versus Saxton Hale mode).
I added gaps between players because that's what the developers intended
Some changes did nothing, so I reverted them to default values
Moved the player lists down a bit and reduced the height of their backgrounds
Screenshots:
Before
After
=> Tweaked post-match list of players

resource/ui/votehud.res
"parameter_width" saved us! (still leaves empty space when there's no scrollbar, but it's still better than the old solution)
=> Better vote menu fix

resource/ui/spectator.res
Because it was so close to the spectator bar that it touched it.
Before:
After:
=> Moved respawn time down

resource/ui/#customizations/killfeed/killfeed_base.res
=> Fixed killfeed overlapping with match status

resource/ui/pvprankpanel.res, resource/ui/scoreboard.res
=> Fixed overlapping of long names

resource/ui/hudobjectiveplayerdestruction.res
To match the position of the money counter in mvm (minmode)
MvM:
Before:
After:
=> Moved player destruction carried container in minmode

resource/clientscheme.res
Adjusts the TF2 fonts to be smaller to fix issues with fonts getting cutoff on Linux. Still doing some testing on this, just putting this here if someone else wants to test it
Before and after examples:
=> Fixes to fonts on Linux

resource/ui/hudmatchsummary.res
Third time's the charm...
This issue is not present in the default hud
The problem was that the changes made to the casual applied to the competitive as well
The solution was found in `if_large`
=> Fixed overlapping of comp badge on the list of players in post-match

resource/ui/hudmatchstatus.res
As you may recall, the past values were taken from flawhud without modification and therefore do not match the style of the default hud
This PR fixes that
Before:
After:
=> Visual tweaks to the pre-match screen

scripts/hudlayout.res
=> Fix arena alive player count being overlapped by the spectator HUD

resource/ui/selbyenhud.res
=> Fix for the Selbyen HUD icons in casual

resource/ui/huditemeffectmeter_powerupbottle.res
Because it was too high and left an empty space
=> Moved the mvm bottle down

resource/ui/spectator.res
Minmode and 4:3
Before:
After:
=> Fixed match status overlapping respawn time in minmode and 4:3

resource/ui/mvmvictorymannuppanel.res
This fix has been added to the `fixes-only` branch https://github.com/CriticalFlaw/TF2HUD.Fixes/commit/da158bcdbf60e2184a400b51db9a19df0148e0f5, but not to the `main` branch
=> Fixed MvM loot item box cutoff on victory screen

resource/ui/hudobjectiveflagpanel.res
before
after
before
after
before
after
before
after
=> Improved consistency of the hudobjectiveflagpanel

resource/ui/hudobjectiveflagpanel.res
=> Minmode Mannpower flagpanel fixes

resource/ui/hudobjectivetimepanel.res
=> Fixed #273 - Server time overlapping overtime and other text

resource/sourceschemebase.res
As per #286. You haven't specified if I should update the server browser font as well @CriticalFlaw so it's just this for now.
Before:
After:
=> Updated sizes of VGUI fonts

resource/ui/pvpcomprankpanel.res
This _potentially_ fixes #298. 
All I did was add `"fov" "45"` under if_mini of the RankModel in pvpcomprankpanel, which theoretically should work.
=> Fixed rank model being too small on Competitive match summary screen

resource/ui/matchmakingcategorypanel.res
Normally, the "View Maps" drop down menu label moves based on the resolution of the screen, causing it to go under the arrow icon when resolution is above 1080p, and move to the right when lower. This fixes that
Before:
After:
=> Fix "View Maps" label in casual map selection moving with resolution
